app:
    security:
        clientId: "task-browser"

# common database configuration for service and liquibase
database:
    name: taskmanager
    host: localhost
    port: 5432
    username: postgres
    password: password

logging:
    level:
        io.r2dbc.postgresql.PARAM: INFO # for parameters
        io.r2dbc.postgresql.QUERY: INFO # for queries
        liquibase: INFO
        org.springframework.data.r2dbc: INFO
        org.springframework.security: DEBUG
        org.springframework.web: INFO
        root: INFO

server:
    error:
        include-binding-errors: never
        include-message: always


spring:
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml
        user: ${database.username}
        password: ${database.password}
        url: jdbc:postgresql://${database.host}:${database.port}/${database.name}?sslmode=disable

    r2dbc:
        username: ${database.username}
        password: ${database.password}
        url: r2dbc:postgresql://${database.host}:${database.port}/${database.name}?sslmode=disable
        # pool.initialSize=5
        # pool.maxSize=5

    security:
        oauth2.resourceserver.jwt.issuer-uri: "http://localhost:8180/auth/realms/TaskManager"

    webflux:
        base-path: /api/v1

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

